[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

# [fs]
# write = ["txLogs.json"]

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]

[rpc_endpoints]
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"
anvil = "${ANVIL_RPC_URL}"

[etherscan]
ethereum_sepolia = { key = "${ETHEREUM_SEPOLIA_ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${BASE_SEPOLIA_ETHERSCAN_API_KEY}" }
base_mainnet = { key = "${BASE_MAINNET_ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
